name: Nightly vulnerability scan

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  scan-and-patch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: ${{ fromJSON(vars.REPO_LIST) }}
      fail-fast: false

    steps:
      - name: Execute scan on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/devops-project

            source venv/bin/activate

            export DATABASE_URL="${{ secrets.POSTGRES_URL }}"
            export GITHUB_TOKEN="${{ secrets.GH_PAT }}"
            export GH_TOKEN="${{ secrets.GH_PAT }}"
            export SLACK_WEBHOOK="${{ secrets.SLACK_WEBHOOK }}"

            python -m scanner.trivy_runner \
              --repo sample-vuln-python

            RUN_ID=$(cat run_id.txt)

            python -m patcher.main \
              --run-id "$RUN_ID" \
              --repo "${{ matrix.repo }}"

